version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/inventory?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres-data: